### PR TITLE
Elizabeth solution

### PR DESCRIPTION
**Pull request by LizzyKate**
This is my solution for my application to the BASICS Specialist in Web Development position.

### CODE REVIEW

**Comment by May-Lee** [comment]
Hi, thank you for your submission.
I've noticed that your commits are directly to the `take-home-assignment` directory.
Could you please move your files to a subdirectory, so that when everyone's PRs are merged, there won't be any conflicts? Thanks!

**Comment by LizzyKate** [comment]
Ok... I will do just that.

**Review by May-Lee — CHANGES_REQUESTED** [review]
Hi, thank you for your submission.
I've noticed that your commits are directly to the `take-home-assignment` directory.
Could you please move your files to a subdirectory, so that when everyone's PRs are merged, there won't be any conflicts? Thanks!

**Comment by LizzyKate** [comment]
> Hi, thank you for your submission.
> I've noticed that your commits are directly to the `take-home-assignment` directory.
> Could you please move your files to a subdirectory, so that when everyone's PRs are merged, there won't be any conflicts? Thanks!

done

**Pull request merged**
